services:
  db:
    image: mysql:8.0
    container_name: library-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: library-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./be
      dockerfile: Dockerfile.be
    # After pushing to Docker Hub, swap the above for:
    # image: <your-dockerhub-username>/library-management-be:latest
    container_name: library-be
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      FRONTEND_URL: ${FRONTEND_URL}
      TZ: Asia/Ho_Chi_Minh
      BACKEND_URL: ${BACKEND_URL}
    ports:
      - "8080:8080"
    volumes:
      - be-logs:/app/logs
      - be-uploads:/app/uploads

  frontend:
    build:
      context: ./fe
      dockerfile: Dockerfile.fe
    # After pushing to Docker Hub, swap the above for:
    # image: <your-dockerhub-username>/library-management-fe:latest
    container_name: library-fe
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  db-data:
  be-logs:
  be-uploads:
