#spring.application.name=library-management
#
#jwt.secret=mySuperSecretKeyThatIsAtLeast32CharactersLongForSecurity123!
#jwt.expiration=86400000
#
#spring.datasource.url=jdbc:mysql://localhost:3306/library_db?zeroDateTimeBehavior=CONVERT_TO_NULL
#spring.datasource.username=root
#spring.datasource.password=Tyler123
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#
#server.servlet.context-path=/api
#
#spring.sql.init.mode=always
#spring.jpa.defer-datasource-initialization=true
#
#logging.level.root=INFO
#logging.file.name=app-logs.log
#
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=baonam6a3@gmail.com
#spring.mail.password=lyvphmsduhdzifto
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#
#app.upload.dir=uploads/book-covers/
#
#spring.data.redis.host=localhost
#spring.data.redis.port=6379
#
#frontend.url=http://localhost:4200


# FOR DEPLOYMENT
spring.application.name=library-management

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}

spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:3306/${DB_NAME:library_management}?zeroDateTimeBehavior=CONVERT_TO_NULL
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.servlet.context-path=/api

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

logging.level.root=INFO
logging.file.name=/app/logs/app-logs.log

spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.upload.dir=/app/uploads/book-covers/

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

frontend.url=${FRONTEND_URL:http://localhost:4200}