INSERT IGNORE INTO roles (id, created_at, created_by, updated_at, updated_by, name, is_default) VALUES
    (1, NOW(), 'SYSTEM', NOW(), 'SYSTEM', 'ROLE_ROOT', false),
    (2, NOW(), 'SYSTEM', NOW(), 'SYSTEM', 'ROLE_ADMIN', false),
    (3, NOW(), 'SYSTEM', NOW(), 'SYSTEM', 'ROLE_LIBRARIAN', false),
    (4, NOW(), 'SYSTEM', NOW(), 'SYSTEM', 'ROLE_USER', true);

INSERT IGNORE INTO features (id, name) VALUES
   (1, 'CREATE_BOOK'),
   (2, 'CREATE_USER'),
   (3, 'CREATE_BORROW'),
   (4, 'CREATE_ROLE'),
   (5, 'CREATE_POST'),
   (6, 'CREATE_COMMENT'),
   (7, 'CREATE_GENRE'),
   (8, 'GET_BOOK'),
   (9, 'GET_USER'),
   (10, 'GET_BORROW'),
   (11, 'GET_BORROW_MULTI'),
   (12, 'GET_ROLE'),
   (13, 'GET_POST'),
   (14, 'GET_COMMENT'),
   (15, 'GET_GENRE'),
   (16, 'GET_POLICY'),
   (17, 'UPDATE_BOOK'),
   (18, 'UPDATE_USER'),
   (19, 'UPDATE_USER_MULTI'),
   (20, 'UPDATE_USER_ROLE'),
   (21, 'UPDATE_BORROW'),
   (22, 'UPDATE_ROLE'),
   (23, 'UPDATE_POST'),
   (24, 'UPDATE_GENRE'),
   (25, 'UPDATE_POLICY'),
   (26, 'DELETE_BOOK'),
   (27, 'DELETE_USER'),
   (28, 'DELETE_USER_MULTI'),
   (29, 'DELETE_BORROW'),
   (30, 'DELETE_ROLE'),
   (31, 'DELETE_POST'),
   (32, 'DELETE_COMMENT'),
   (33, 'DELETE_GENRE'),
   (34, 'ASSIGN_FEATURE'),
   (35, 'UNASSIGN_FEATURE'),
   (36, 'EXPORT_USER'),
   (37, 'EXPORT_BOOK'),
   (38, 'EXPORT_BORROW');

INSERT IGNORE INTO genres (id, name) VALUES
     (1, 'Sci-fi'),
     (2, 'Romance'),
     (3, 'Manga'),
     (4, 'Historical Fiction'),
     (5, 'War Story'),
     (6, 'Fantasy'),
     (7, 'Mystery'),
     (8, 'Thriller'),
     (9, 'Dystopian'),
     (10, 'Self-Help');

INSERT IGNORE INTO books (id, title, author, copies, created_at, cover_url) VALUES
    (1, 'Project Hail Mary', 'Andy Weir', 10, DATE_SUB(NOW(), INTERVAL 6 DAY), '1.jpg'),
    (2, 'We Are Legion (We Are Bob)', 'Dennis E. Taylor', 5, DATE_SUB(NOW(), INTERVAL 6 DAY), '2.jpg'),
    (3, 'The Song of Achilles', 'Madeline Miller', 1, DATE_SUB(NOW(), INTERVAL 18 DAY), '3.jpg'),
    (4, 'The Martian', 'Andy Weir', 0, DATE_SUB(NOW(), INTERVAL 10 DAY), '4.jpg'),
    (5, 'Dune', 'Frank Herbert', 0, DATE_SUB(NOW(), INTERVAL 19 DAY), '5.jpg'),
    (6, 'Neuromancer', 'William Gibson', 0, DATE_SUB(NOW(), INTERVAL 5 DAY), '6.jpg'),
    (7, 'Pride and Prejudice', 'Jane Austen', 0, DATE_SUB(NOW(), INTERVAL 1 DAY), '7.jpg'),
    (8, 'The Seven Husbands of Evelyn Hugo', 'Taylor Jenkins Reid', 0, DATE_SUB(NOW(), INTERVAL 17 DAY), '8.jpg'),
    (9, 'Spy x Family, Vol. 1', 'Tatsuya Endo', 0, DATE_SUB(NOW(), INTERVAL 1 DAY), '9.jpg'),
    (10, 'Demon Slayer: Kimetsu no Yaiba, Vol. 1', 'Koyoharu Gotouge', 0, DATE_SUB(NOW(), INTERVAL 2 DAY), '10.jpg'),
    (11, 'Chainsaw Man, Vol. 1', 'Tatsuki Fujimoto', 11, DATE_SUB(NOW(), INTERVAL 9 DAY), '11.jpg'),
    (12, 'The Book Thief', 'Markus Zusak', 5, DATE_SUB(NOW(), INTERVAL 2 DAY), '12.jpg'),
    (13, 'All the Light We Cannot See', 'Anthony Doerr', 0, DATE_SUB(NOW(), INTERVAL 18 DAY), '13.jpg'),
    (14, 'The Nightingale', 'Kristin Hannah', 6, DATE_SUB(NOW(), INTERVAL 20 DAY), '14.jpg'),
    (15, 'Circe', 'Madeline Miller', 4, DATE_SUB(NOW(), INTERVAL 9 DAY), '15.jpg'),
    (16, 'Snow Crash', 'Neal Stephenson', 3, DATE_SUB(NOW(), INTERVAL 0 DAY), '16.jpg'),
    (17, 'A Court of Thorns and Roses', 'Sarah J. Maas', 8, DATE_SUB(NOW(), INTERVAL 1 DAY), '17.jpg'),
    (18, 'Kaguya-sama: Love Is War, Vol. 1', 'Aka Akasaka', 0, DATE_SUB(NOW(), INTERVAL 6 DAY), '18.jpg'),
    (19, 'The Hobbit', 'J.R.R. Tolkien', 12, DATE_SUB(NOW(), INTERVAL 5 DAY), '19.jpg'),
    (20, 'The Fellowship of the Ring', 'J.R.R. Tolkien', 8, DATE_SUB(NOW(), INTERVAL 4 DAY), '20.jpg'),
    (21, 'Gone Girl', 'Gillian Flynn', 6, DATE_SUB(NOW(), INTERVAL 3 DAY), '21.jpg'),
    (22, 'The Girl with the Dragon Tattoo', 'Stieg Larsson', 0, DATE_SUB(NOW(), INTERVAL 9 DAY), '22.jpg'),
    (23, '1984', 'George Orwell', 15, DATE_SUB(NOW(), INTERVAL 7 DAY), '23.jpg'),
    (24, 'Atomic Habits', 'James Clear', 0, DATE_SUB(NOW(), INTERVAL 8 DAY), '24.jpg');

INSERT IGNORE INTO books_genres (book_id, genre_id) VALUES
    (1, 1),
    (2, 1),
    (3, 2), (3, 4), (3, 5),
    (4, 1),
    (5, 1),
    (6, 1),
    (7, 2), (7, 4),
    (8, 2), (8, 4),
    (9, 3),
    (10, 3),
    (11, 3),
    (12, 4), (12, 5),
    (13, 4), (13, 5),
    (14, 4), (14, 5),
    (15, 4),
    (16, 1),
    (17, 2),
    (18, 2), (18, 3),
    (19, 6),
    (20, 6),
    (21, 7), (21, 8),
    (22, 7), (22, 8),
    (23, 1), (23, 9),
    (24, 10),
    (25, 4);

INSERT IGNORE INTO users (id, full_name, username, address, email, phone_number, password, role_id, created_at, is_deleted, is_active) VALUES
    (1, 'Tyler Dao', 'tyler', '32 Noecker Street', 'baonamfpt@gmail.com', '5483843681', '$2a$10$SWzx7vnpEzMZlj6F1tGrSOcwWclGU2lS0FKSck2eyz16V0gi3A3rm', '1', NOW(), false, true);

INSERT IGNORE INTO policies (policy_key, policy_value) VALUES
    ("borrow_duration", "14"),
    ("late_penalty_per_day", "10000");